"""add table CarPart3

Revision ID: 8a949d912431
Revises: 703375165201
Create Date: 2026-02-10 22:48:18.619459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a949d912431'
down_revision: Union[str, Sequence[str], None] = '703375165201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cars_parts_car_id_fkey'), 'car_part', type_='foreignkey')
    op.create_foreign_key(None, 'car_part', 'parts', ['part_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_part', type_='foreignkey')
    op.create_foreign_key(op.f('cars_parts_car_id_fkey'), 'car_part', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###
