"""add table CarPart4

Revision ID: efe888e38197
Revises: 8a949d912431
Create Date: 2026-02-10 22:53:23.639512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efe888e38197'
down_revision: Union[str, Sequence[str], None] = '8a949d912431'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'car_part', 'cars', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'car_part', type_='foreignkey')
    # ### end Alembic commands ###
